import "@/app/globals.css";
import { Navigation } from "@/components/Navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const PortfoliosLayout = ({ children }) => {
  return <div className="todos-page-container">{children}</div>;
};

export default PortfoliosLayout;
